### ISSUE TITLE
been searching everywhere is there any way do you know if da Vinci can be used with the file search..

### ISSUE THREAD

**Issue by blender-tv-studio** [OrbiterToad/davinci-chatbot#2]
I have some functions using the assistance API and I use GPT 3.5 with them and they do file search but I heard Davinci might be better at searching files do you have any code examples that you could show me using da Vinci to look up a file at a certain vector ID. I'm talking about how you upload files to the playground and get the vector ID I would like to use da Vinci in order to look up those files and copy and paste data you know like an advanced file search.... Basically I would like to give it code .....in blender python and have it look up a file containing The blender 4.1 manual and see if based on the code it could likely find relevant sections of the manual to recommend to show Whether or not the actions done in code are done properly per the blender manual instructions... Any advice on how I could use da Vinci to look up files would be appreciated.... Or would you be more inclined to recommend that I just create a fine tuning job using the GPT 3.5 model again any help is appreciated

**Comment by OrbiterToad** [comment]
davinci is better suited for creative tasks like creating ideas or having conversations, rather than searching for files. 
its probably best to use a finetuned gpt 3.5 model in your case.

**Comment by blender-tv-studio** [comment]
Thank you very much. I appreciate that now I could have a better approach
to designing my system..
